# Generated by Django 4.1.13 on 2024-01-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_location', models.CharField(max_length=255)),
                ('total_salary', models.FloatField()),
                ('City', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
            options={
                'db_table': 'JobInfo',
            },
        ),
    ]
